//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorsOfAccident
    {
        public int Id { get; set; }
        public int DriverId { get; set; }
        public int RoadAccinetId { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual RoadAccidents RoadAccidents { get; set; }
    }
}
