//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarColors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarColors()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public int ColorNum { get; set; }
        public string ColorCode { get; set; }
        public string NameRU { get; set; }
        public string ColorNameRU { get; set; }
        public string IsMettalic { get; set; }
        public string NameEN { get; set; }
        public string ColorNameEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }

        public override string ToString()
        {
            string s = this.IsMettalic == "1" ? "металлический" : "матовый";
            return $"Цвет №{this.ColorNum}: цветовой код - {this.ColorCode}, название - {this.NameRU}, полное название - {this.ColorNameRU}, " + s;
        }
    }
}
