//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drivers()
        {
            this.ActorsOfAccident = new HashSet<ActorsOfAccident>();
        }
    
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public string PassportSerial { get; set; }
        public string PassportNumber { get; set; }
        public string PostCode { get; set; }
        public string Address { get; set; }
        public string AddressLife { get; set; }
        public string Company { get; set; }
        public string JobName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public byte[] Photo { get; set; }
        public string Description { get; set; }
        public Nullable<int> Licence { get; set; }
        public Nullable<int> Car { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActorsOfAccident> ActorsOfAccident { get; set; }
        public virtual Cars Cars { get; set; }
        public virtual Licences Licences { get; set; }
    }
}
