//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GIBDDEntities : DbContext
    {
        private static GIBDDEntities _context;
        public GIBDDEntities()
            : base("name=GIBDDEntities")
        {
        }
        public static GIBDDEntities GetContext()
        {
            if (_context == null)
                _context = new GIBDDEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActorsOfAccident> ActorsOfAccident { get; set; }
        public virtual DbSet<CarColors> CarColors { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<EngineTypes> EngineTypes { get; set; }
        public virtual DbSet<Inspector> Inspector { get; set; }
        public virtual DbSet<Licences> Licences { get; set; }
        public virtual DbSet<RegionCodes> RegionCodes { get; set; }
        public virtual DbSet<RoadAccidentClassifications> RoadAccidentClassifications { get; set; }
        public virtual DbSet<RoadAccidents> RoadAccidents { get; set; }
    }
}
