//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionCodes
    {
        public int Id { get; set; }
        public string RegionNameEN { get; set; }
        public string RegionNameRU { get; set; }
        public string SubjectCode { get; set; }
        public string Code { get; set; }
        public string OkatoCode { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
    }
}
