//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoadAccidents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoadAccidents()
        {
            this.ActorsOfAccident = new HashSet<ActorsOfAccident>();
        }
    
        public int Id { get; set; }
        public string CrimeScene { get; set; }
        public System.DateTime DateOfAccident { get; set; }
        public Nullable<System.TimeSpan> TimeOfAccident { get; set; }
        public string Description { get; set; }
        public int NumberOfVictims { get; set; }
        public Nullable<int> ClassificationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActorsOfAccident> ActorsOfAccident { get; set; }
        public virtual RoadAccidentClassifications RoadAccidentClassifications { get; set; }
    }
}
